name = "speech-feedback-app"
compatibility_date = "2023-10-30"

[site]
bucket = "./dist"
entry-point = "."

[build]
command = "npm run build"
output_dir = "dist"

[env.production]
vars = { BACKEND_URL = "https://your-backend-url.com" }

[env.development]
vars = { BACKEND_URL = "http://localhost:5000" } 