name = "model-convert"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_directory = "dist"
pages_build_output_dir = "dist"

# WebSocket connections allowed via automatic upgrading
[site]
bucket = "./dist"

# Define the worker for handling Socket.IO connections
[[functions]]
pattern = "/socket.io/*"
script = "worker.js"

[env.production]
vars = { VITE_BACKEND_URL = "https://name-model-convert-backend.onrender.com", VITE_API_URL = "https://name-model-convert-backend.onrender.com" } 