name = "model-convert-app"
compatibility_date = "2024-01-01"

# Explicitly setting Pages configuration
[build]
command = "chmod +x cloudflare-build.sh && ./cloudflare-build.sh"
output_directory = "dist"

# Route all requests to index.html for SPA
[site]
bucket = "./dist"

[site.static_files]
"/*" = "index.html" 